#!/usr/bin/env python

# Autora: Marta María Álvarez Crespo
# Descripción: Nodo de ROS que inicia el proceso FindWall.
# Última modificación: 07 / 04 / 2024

import rospy
from myturtle3 import move_stop


def inicia_nodo():
    """
    Inicializa el nodo de ROS e inicia el proceso FindWall.

    Esta función inicializa el nodo de ROS con el nombre "move_node" y comienza el proceso FindWall.
    Si ocurre una excepción ROSInterruptException, se registra un mensaje de error.

    Args:
        None

    Returns:
        None
    """
    try:
        rospy.init_node("move_node")
        reach_wall = move_stop.FindWall()
        reach_wall.start()

    except rospy.ROSInterruptException:
        rospy.logerr("Error inicializando el nodo")


if __name__ == "__main__":
    inicia_nodo()
