#! /usr/bin/env python

import rospy
from hello_world import publisher

def InitNode():
    try:
        rospy.init_node('pub')
        publisher.publisher()
    except rospy.ROSInterruptException:
        rospy.logerr('Error')

if __name__ == "__main__":
    InitNode()
