#! /usr/bin/env python

import rospy
from hello_world import publisher

def init_node():
    """_summary_
    """
    try:
        rospy.init_node('pub')
        publisher.publisher()
    except rospy.ROSInterruptException:
        rospy.logerr('Error')

if __name__ == "__main__":
    init_node()
