// Generated by gencpp from file practica_03/GetSensorValueResponse.msg
// DO NOT EDIT!


#ifndef PRACTICA_03_MESSAGE_GETSENSORVALUERESPONSE_H
#define PRACTICA_03_MESSAGE_GETSENSORVALUERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace practica_03
{
template <class ContainerAllocator>
struct GetSensorValueResponse_
{
  typedef GetSensorValueResponse_<ContainerAllocator> Type;

  GetSensorValueResponse_()
    : value(0)  {
    }
  GetSensorValueResponse_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef int8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::practica_03::GetSensorValueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practica_03::GetSensorValueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetSensorValueResponse_

typedef ::practica_03::GetSensorValueResponse_<std::allocator<void> > GetSensorValueResponse;

typedef boost::shared_ptr< ::practica_03::GetSensorValueResponse > GetSensorValueResponsePtr;
typedef boost::shared_ptr< ::practica_03::GetSensorValueResponse const> GetSensorValueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practica_03::GetSensorValueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practica_03::GetSensorValueResponse_<ContainerAllocator1> & lhs, const ::practica_03::GetSensorValueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practica_03::GetSensorValueResponse_<ContainerAllocator1> & lhs, const ::practica_03::GetSensorValueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practica_03

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practica_03::GetSensorValueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_03::GetSensorValueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_03::GetSensorValueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28331970c7aec433ff1bf9106c582ad5";
  }

  static const char* value(const ::practica_03::GetSensorValueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28331970c7aec433ULL;
  static const uint64_t static_value2 = 0xff1bf9106c582ad5ULL;
};

template<class ContainerAllocator>
struct DataType< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practica_03/GetSensorValueResponse";
  }

  static const char* value(const ::practica_03::GetSensorValueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 value\n"
;
  }

  static const char* value(const ::practica_03::GetSensorValueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSensorValueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practica_03::GetSensorValueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practica_03::GetSensorValueResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICA_03_MESSAGE_GETSENSORVALUERESPONSE_H
