// Generated by gencpp from file practica_03/GetSensorValueRequest.msg
// DO NOT EDIT!


#ifndef PRACTICA_03_MESSAGE_GETSENSORVALUEREQUEST_H
#define PRACTICA_03_MESSAGE_GETSENSORVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace practica_03
{
template <class ContainerAllocator>
struct GetSensorValueRequest_
{
  typedef GetSensorValueRequest_<ContainerAllocator> Type;

  GetSensorValueRequest_()
    : name()  {
    }
  GetSensorValueRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::practica_03::GetSensorValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practica_03::GetSensorValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSensorValueRequest_

typedef ::practica_03::GetSensorValueRequest_<std::allocator<void> > GetSensorValueRequest;

typedef boost::shared_ptr< ::practica_03::GetSensorValueRequest > GetSensorValueRequestPtr;
typedef boost::shared_ptr< ::practica_03::GetSensorValueRequest const> GetSensorValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practica_03::GetSensorValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practica_03::GetSensorValueRequest_<ContainerAllocator1> & lhs, const ::practica_03::GetSensorValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practica_03::GetSensorValueRequest_<ContainerAllocator1> & lhs, const ::practica_03::GetSensorValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practica_03

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practica_03::GetSensorValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_03::GetSensorValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_03::GetSensorValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::practica_03::GetSensorValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practica_03/GetSensorValueRequest";
  }

  static const char* value(const ::practica_03::GetSensorValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::practica_03::GetSensorValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSensorValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practica_03::GetSensorValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practica_03::GetSensorValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICA_03_MESSAGE_GETSENSORVALUEREQUEST_H
