// Generated by gencpp from file practica_02/SensorMessage.msg
// DO NOT EDIT!


#ifndef PRACTICA_02_MESSAGE_SENSORMESSAGE_H
#define PRACTICA_02_MESSAGE_SENSORMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace practica_02
{
template <class ContainerAllocator>
struct SensorMessage_
{
  typedef SensorMessage_<ContainerAllocator> Type;

  SensorMessage_()
    : id(0)
    , name()
    , temperature(0.0)  {
    }
  SensorMessage_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , temperature(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _temperature_type;
  _temperature_type temperature;





  typedef boost::shared_ptr< ::practica_02::SensorMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practica_02::SensorMessage_<ContainerAllocator> const> ConstPtr;

}; // struct SensorMessage_

typedef ::practica_02::SensorMessage_<std::allocator<void> > SensorMessage;

typedef boost::shared_ptr< ::practica_02::SensorMessage > SensorMessagePtr;
typedef boost::shared_ptr< ::practica_02::SensorMessage const> SensorMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practica_02::SensorMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practica_02::SensorMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::practica_02::SensorMessage_<ContainerAllocator1> & lhs, const ::practica_02::SensorMessage_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.temperature == rhs.temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::practica_02::SensorMessage_<ContainerAllocator1> & lhs, const ::practica_02::SensorMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace practica_02

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::practica_02::SensorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practica_02::SensorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_02::SensorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practica_02::SensorMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_02::SensorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practica_02::SensorMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practica_02::SensorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de8fe049e001b611ef86fe55ef6c3200";
  }

  static const char* value(const ::practica_02::SensorMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde8fe049e001b611ULL;
  static const uint64_t static_value2 = 0xef86fe55ef6c3200ULL;
};

template<class ContainerAllocator>
struct DataType< ::practica_02::SensorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practica_02/SensorMessage";
  }

  static const char* value(const ::practica_02::SensorMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practica_02::SensorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
"float32 temperature\n"
;
  }

  static const char* value(const ::practica_02::SensorMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practica_02::SensorMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practica_02::SensorMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practica_02::SensorMessage_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICA_02_MESSAGE_SENSORMESSAGE_H
